---
title: "make_lists"
author: "Alish Palmos"
date: "14/04/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Make lists

```{r}

make_list = FALSE

if(make_list == TRUE) {
list <- read.table("/scratch/groups/ukbiobank/usr/alish/AD_MR/protein_brainvol_MR/protein_AD/deco/list.txt")

n <- 40
nr <- nrow(list)
split <- split(list, rep(1:ceiling(nr/n), each=n, length.out=nr))

list1 <- split$`1`
list2 <- split$`2`
list3 <- split$`3`
list4 <- split$`4`
list5 <- split$`5`
list6 <- split$`6`
list7 <- split$`7`
list8 <- split$`8`
list9 <- split$`9`
list10 <- split$`10`

all <- read.table("/scratch/groups/ukbiobank/usr/alish/AD_MR/protein_brainvol_MR/protein_AD/deco/deco.txt")

temp <- merge(list1, all, by = "V1", all.x = TRUE)
list1 <- temp[, c(1,3,2)]

temp <- merge(list2, all, by = "V1", all.x = TRUE)
list2 <- temp[, c(1,3,2)]

temp <- merge(list3, all, by = "V1", all.x = TRUE)
list3 <- temp[, c(1,3,2)]

temp <- merge(list4, all, by = "V1", all.x = TRUE)
list4 <- temp[, c(1,3,2)]

temp <- merge(list5, all, by = "V1", all.x = TRUE)
list5 <- temp[, c(1,3,2)]

temp <- merge(list6, all, by = "V1", all.x = TRUE)
list6 <- temp[, c(1,3,2)]

temp <- merge(list7, all, by = "V1", all.x = TRUE)
list7 <- temp[, c(1,3,2)]

temp <- merge(list8, all, by = "V1", all.x = TRUE)
list8 <- temp[, c(1,3,2)]

temp <- merge(list9, all, by = "V1", all.x = TRUE)
list9 <- temp[, c(1,3,2)]

temp <- merge(list10, all, by = "V1", all.x = TRUE)
list10 <- temp[, c(1,3,2)]

write.table(x = list1, file = "/scratch/groups/ukbiobank/usr/alish/AD_MR/protein_brainvol_MR/protein_AD/deco/list1.txt", quote = FALSE, row.names = FALSE, col.names = FALSE, sep = "\t ")

write.table(x = list2, file = "/scratch/groups/ukbiobank/usr/alish/AD_MR/protein_brainvol_MR/protein_AD/deco/list2.txt", quote = FALSE, row.names = FALSE, col.names = FALSE, sep = "\t ")

write.table(x = list3, file = "/scratch/groups/ukbiobank/usr/alish/AD_MR/protein_brainvol_MR/protein_AD/deco/list3.txt", quote = FALSE, row.names = FALSE, col.names = FALSE, sep = "\t ")

write.table(x = list4, file = "/scratch/groups/ukbiobank/usr/alish/AD_MR/protein_brainvol_MR/protein_AD/deco/list4.txt", quote = FALSE, row.names = FALSE, col.names = FALSE, sep = "\t ")

write.table(x = list5, file = "/scratch/groups/ukbiobank/usr/alish/AD_MR/protein_brainvol_MR/protein_AD/deco/list5.txt", quote = FALSE, row.names = FALSE, col.names = FALSE, sep = "\t ")

write.table(x = list6, file = "/scratch/groups/ukbiobank/usr/alish/AD_MR/protein_brainvol_MR/protein_AD/deco/list6.txt", quote = FALSE, row.names = FALSE, col.names = FALSE, sep = "\t ")

write.table(x = list7, file = "/scratch/groups/ukbiobank/usr/alish/AD_MR/protein_brainvol_MR/protein_AD/deco/list7.txt", quote = FALSE, row.names = FALSE, col.names = FALSE, sep = "\t ")

write.table(x = list8, file = "/scratch/groups/ukbiobank/usr/alish/AD_MR/protein_brainvol_MR/protein_AD/deco/list8.txt", quote = FALSE, row.names = FALSE, col.names = FALSE, sep = "\t ")

write.table(x = list9, file = "/scratch/groups/ukbiobank/usr/alish/AD_MR/protein_brainvol_MR/protein_AD/deco/list9.txt", quote = FALSE, row.names = FALSE, col.names = FALSE, sep = "\t ")

write.table(x = list10, file = "/scratch/groups/ukbiobank/usr/alish/AD_MR/protein_brainvol_MR/protein_AD/deco/list10.txt", quote = FALSE, row.names = FALSE, col.names = FALSE, sep = "\t ")

}

```
